title: Paul's Trails
header: LA VITA
author: P.Paul

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: /page:num

permalink: /:year/:month/:day/:title

highlighter: none
markdown: kramdown
kramdown:
  header_offset: 1
  toc_levels: 1..3
  syntax_highlighter_opts:
    disable: true

sass:
  style: compressed

thirdparty:
  giscus:
    repo: peng-ao/blog
    repo-id: MDEwOlJlcG9zaXRvcnk0MDQwMzExNDM=
    category: Comment
    category-id: DIC_kwDOGBUGp84Cj8AW
  goatcounter:
    code: peng-ao
